Added scripts to set PYTHONUSERSITE
openwpm/OpenWPM pull request #726
Opened 2020-08-07 19:55 UTC by vringar

This also puts in place a more general infrastructure
should we ever become more opinionated and
automatically hook up things like pre-commit

Closes #689

2020-08-10 20:00 UTC, birdsarah commented
I don't get this, we already set PYTHONUSERSITE where it's needed to solve the issue: https://github.com/mozilla/OpenWPM/blob/master/scripts/repin.sh#L12-L15

Why is the existing solution insufficient.

2020-08-11 01:46 UTC, birdsarah commented
I've just seen the tread on matrix so am caught up on your motivations.

2020-08-31 22:00 UTC, birdsarah commented on scripts/deploy_env_scripts.py
> +CONDA_SCRIPT_DIR = "./etc/conda"
I still have a path in my head of how we can support windows. I think it would be good if we didn't add things that inhibit that possibility.

2020-12-09 22:10 UTC, faith requested changes
Tests seem to fail too

2020-12-14 13:49 UTC, vringar commented
Yeah, this PR is pretty broken. Do you want to pick it up and play around with it?

2022-09-21 19:07 UTC, closed without merging